version: '3.7'

services:

  php:
    build:
      context: ./
    container_name: php-openswoole
    volumes:
      - ".:/var/www/html"
    expose:
      - 8001
    ports:
      - "8001:8001"
    networks:
      - openswoole-network

networks:
  openswoole-network:
    driver: bridge